server:
  port: 8080
  servlet:
    context-path: /quanlyphongtro

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/quanlyphongtro"
    username: root
    password: 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl